# Generated by Django 6.0.6 on 2026-07-14 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('goal', models.CharField(choices=[('L', 'Lose Weight'), ('G', 'Gain Weight'), ('MT', 'Maintain Weight')], max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly', 'Lightly active (light exercise/sports 1-3 days/week)'), ('Moderately', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('High', 'Very active (hard exercise/sports 6-7 days a week)'), ('Extra', 'Extra active (very hard exercise/sports)')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dietitian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.dietitianprofile')),
            ],
        ),
    ]
