# Generated by Django 6.0.7 on 2026-08-13 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_meal_food_remove_meal_quantity_g_mealitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
