# Generated by Django 6.0.7 on 2026-08-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_exerciseprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='exercises',
        ),
        migrations.CreateModel(
            name='ExerciseProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exerciseprogram')),
            ],
        ),
    ]
